# .github/workflows/main.yml
name: Update Navigation and Deploy

on:
  push:
    branches:
      - main # 或者你的默认分支
    paths: # 仅当这些路径下的文件发生变化时触发
      - '**.html'
      - '!index.html' # 如果是手动修改 index.html，不直接触发 (避免与机器人提交冲突)
      - 'generate_nav.py' # 如果生成脚本变化，也运行

jobs:
  build-nav:
    # 这个条件防止作业因包含 [skip ci] 的提交消息而运行 (这是机器人提交的标志)
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许 Action 推送更改到仓库

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有历史记录，以便进行准确的差异比较

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 或其他兼容版本

      - name: Install dependencies
        run: pip install beautifulsoup4

      - name: Generate navigation links
        id: generate_nav # 给这个步骤一个ID
        run: python generate_nav.py

      - name: Commit and push if index.html changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update: Refresh navigation links [skip ci]" # 已将此字符串用引号括起
          file_pattern: index.html # 仅当 index.html 发生变化时才提交
          # commit_user_name: GitHub Actions Bot # 可选
          # commit_user_email: actions@github.com # 可选
          push_options: '--force' # 如果需要强制推送 (通常不推荐，但如果分支保护规则导致问题可以考虑)
                                  # 正常情况下，如果Action是唯一修改index.html的，不需要force
